### PR TITLE
LRDOCS-4691 4693 Troubleshooting: Use osgi services instead of service utils

### PR DESCRIPTION
**Pull request by jhinkey**
Hi Shuyang,

I've simplified these troubleshooting tutorials to direct developers to use ServiceTrackers in place of ServiceUtils. Thanks for reviewing!

https://issues.liferay.com/browse/LRDOCS-4691
https://issues.liferay.com/browse/LRDOCS-4693

### CODE REVIEW

**Comment by jhinkey** [comment]
Hi @shuyangzhou ,

Can you review the two troubleshooting articles in the last commit (_LRDOCS-4691 LRDOCS-4693 port to 7.1. Direct developers to use Service…_)?

Thanks in advance!

**Comment by jhinkey** [comment]
Hi Shuyang,
Can you have someone review this?

**Comment by shuyangzhou** [comment]
@tinatian will take care of it.
And @jhinkey can you send pulls to @tinatian from now on, I am not really monitoring this repo.

**Comment by jhinkey** [comment]
OK. I'll do that, @shuyangzhou . I'll send them to you shortly, @tinatian. Thanks.

**Pull request closed without merging**
