### PR TITLE
71 message bus

### PR DESCRIPTION
**Pull request by jhinkey**
Hi Shuyang,

Mike Han asked for someone else to review the Message Bus tutorials for 7.1. This PR is a straightforward port of the Message Bus tutorials from 7.0 to 7.1. All the changes are in 05b8ef4

Would you or a teammate give a quick check on anything new in 7.1 that needs to be added/changed. Thanks!

https://issues.liferay.com/browse/LRDOCS-4706

### CODE REVIEW

**Comment by tinatian** [comment]
@jhinkey I am going to close this pull, could you please fix the typo and send it me?

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Comment by jhinkey** [comment]
@tinatian What typo?

**Comment by tinatian** [comment]
@jhinkey You do not have this variable defined : kaleoGraphWalkerDestinationConfiguration, you use destinationConfiguration instead. So you need to change this line to:
_destinationFactory.createDestination(destinationConfiguration);

**Pull request closed without merging**
