### PR TITLE
Troubleshooting bundles

### PR DESCRIPTION
**Pull request by jhinkey**
Hi Shuyang,

I've ported these troubleshooting tutorial from 7.0 to 7.1. In most cases, I improved their wording and updating their links to 7.1 articles. 

To compare an updated article with its original, click on the commit _after_ the commit that ends in _original from 7.0_. Each article has its own LRDOCS ticket.

If you delegate review to a team member, please let me know.

Thanks!

Jim

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@tinatian please take over these doc pulls, thanks!

**Comment by tomwang2011** [comment]
Hi @jhinkey I am looking over the changes and I am wondering if there is a way to view the links and if we needed to verify the linked pages (with the 7-1 change) exists, as they are relative paths we cannot hit and verify any of them.

Thanks!

**Comment by jhinkey** [comment]
Hi @tomwang2011 - You can verify them by appending them to this URL: `https://dev.liferay.com`

**Comment by tomwang2011** [comment]
Hi @jhinkey - we reviewed these changes and they all seems to be correct to us, should we close these pulls after review?

**Comment by jhinkey** [comment]
Hi @tomwang2011 - Yes. Sorry I forgot to add the JIRA ticket links to the PR description. Typically you'd assign the tickets back to me with status _Needs more work_ or keeping status _SME review_. Then I'd take it from there. I'll close it for now and mention the PR I send onward.

**Comment by jhinkey** [comment]
Thanks! I forwarded the branch in https://github.com/sez11a/liferay-docs/pull/3399

**Pull request closed without merging**
