### PR TITLE
Using component config files

### PR DESCRIPTION
**Pull request by jhinkey**
https://issues.liferay.com/browse/LRDOCS-4690

### CODE REVIEW

**Comment by lanceji92674957** [comment]
Hi James,

The link of "configuration file's syntax" on 13-using-files-to-config-components.markdown doe not work for me.
Please check if it's working.

Thanks.
Lance

**Comment by jhinkey** [comment]
Hi Lance,

The link is good. It's a cross reference to another anchored heading in this article---line 14:

`## Configuration File Formats [](id=configuration-file-formats)`

Our Markdown to HTML converter generates a header that's wrapped with an anchor that has this attribute: `href="#configuration-file-formats"`. 

For example, you can view the source of any sub heading in one of our official docs on dev.liferay.com. 

Any other review comments? Thanks.

**Comment by lanceji92674957** [comment]
Hi @jhinkey, thanks for the explanation. Everything seems right to me.

**Comment by jhinkey** [comment]
Great! Thanks, @lanceji92674957 !

**Comment by jhinkey** [comment]
Sent https://github.com/sez11a/liferay-docs/pull/3421

**Pull request closed without merging**
