### PR TITLE
LRDOCS-4705 Data Scopes

### PR DESCRIPTION
**Pull request by jhinkey**
Hi Shuyang,

Here is the Data Scopes tutorial for review.

https://issues.liferay.com/browse/LRDOCS-4705

### CODE REVIEW

**Comment by lanceji92674957** [comment]
Hi James,

Please update links on these two lines:
[Understanding `ServiceContext`](/develop/tutorials/-/knowledge_base/7-0/understanding-servicecontext)
[Structures and Templates](/discover/portal/-/knowledge_base/7-0/designing-uniform-content) 

Thanks.
Lance

**Comment by jhinkey** [comment]
Hi Lance,


These two links result in this in the Knowledge Base on dev.liferay.com …

- https://dev.liferay.com/develop/tutorials/-/knowledge_base/7-1/understanding-servicecontext
- https://dev.liferay.com/discover/portal/-/knowledge_base/7-1/designing-uniform-content

The Knowledge Base article importer appends the site's URL to each relative URL.

For example, it appends `https://dev.liferay.com` to the relative URL `/develop/tutorials/-/knowledge_base/7-1/understanding-servicecontext
`. 

You can test any of the relative paths by pasting them after https://dev.liferay.com in your browser. 

Any other review comments/changes? Thanks.

**Comment by lanceji92674957** [comment]
Hi @jhinkey , I think all the changes seem right to me now, thanks

**Comment by jhinkey** [comment]
Thanks! Sent https://github.com/sez11a/liferay-docs/pull/3422

**Pull request closed without merging**
