### PR TITLE
System Check and Detecting Unresolved Components

### PR DESCRIPTION
**Pull request by jhinkey**
Hi Shuyang,

Here are two troubleshooting articles for review. The System Check article is new and the other is updated for 7.1. Also, is `system:check` available in the same way in 7.0?

https://issues.liferay.com/browse/LRDOCS-5238
https://issues.liferay.com/browse/LRDOCS-4689

Please review or delegate for a team member to review. Thanks!

Jim

### CODE REVIEW

**Comment by shuyangzhou** [comment]
In a recent change, Brian asked us to disable this by default to save the startup time.
So right now, in portal.properties we have this:
```module.framework.properties.initial.system.check.enabled=false```
and we enabled it in portal-developer.properties
```module.framework.properties.initial.system.check.enabled=true```

**Comment by lanceji92674957** [comment]
Hi Jim, 

For the file: detecting-unresolved-osgi-components.markdown, I noticed that the URLs on line 4 and line 137 are not updated to 7-1. Please check if it should be updated.

Thanks.
Lance

**Comment by jhinkey** [comment]
@shuyangzhou - What's the recommended way to use `portal-developer.properties`? Is it by adding this to your `portal-ext.properties`?

    include-and-override=portal-developer.properties

**Comment by jhinkey** [comment]
@shuyangzhou , @lanceji92674957 - Thanks for your review comments. I've updated the docs based on them. Please check. Thanks!

**Comment by jhinkey** [comment]
@lanceji92674957 Are these changes good? Thanks.

**Comment by jhinkey** [comment]
... I see you assigned the ticket back to me, so you must be good with the changes. :-)

I'll push them along for final review and publishing. Thanks.

**Comment by lanceji92674957** [comment]
@jhinkey yes, I already changed status on 
https://issues.liferay.com/browse/LRDOCS-5238
https://issues.liferay.com/browse/LRDOCS-4689

Thanks

**Pull request closed without merging**
